# Generated by Django 3.1 on 2020-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_auto_20201029_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='attachments',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='multiplefiles',
            name='attachments',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
