# Generated by Django 3.1 on 2020-10-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_auto_20201030_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleFiles',
        ),
    ]
